isc.VLayout.create({
    width: '100%',
    height: '100%',
    membersMargin: 2,
    layoutMargin: 2,
    backgroundColor: 'rgb(245, 245, 245)',
    members: [
        isc.VLayout.create({
            height:80
        })
        ,
        isc.Menubar.create({
            //width: "100%",
            backgroundColor: 'rgb(70, 70, 70)',
            menus: [
                {
                    title:'<span class="glyphicon">\ue021</span>',
                    width:60,
                    styleName:"glyphicon"
                }
                ,
                {
                    title: 'File',
                    width: 180,
                    showShadow: true,
                    shadowDepth: 10,
                    data: [
                        {title: "New", keyTitle: "Ctrl+N", icon: "icons/16/document_plain_new.png"},
                        {title: "Open", keyTitle: "Ctrl+O", icon: "icons/16/folder_out.png"},
                        {isSeparator: true},
                        {title: "Save", keyTitle: "Ctrl+S", icon: "icons/16/disk_blue.png"},
                        {title: "Save As", icon: "icons/16/save_as.png"},
                        {isSeparator: true},
                        {
                            title: "Recent Documents", icon: "icons/16/folder_document.png", submenu: [
                            {title: "data.xml", checked: true},
                            {title: "Component Guide.doc"},
                            {title: "SmartClient.doc", checked: true},
                            {title: "AJAX.doc"}
                        ]
                        },
                        {isSeparator: true},
                        {
                            title: "Export as...", icon: "icons/16/export1.png", submenu: [
                            {title: "XML"},
                            {title: "CSV"},
                            {title: "Plain text"}
                        ]
                        },
                        {isSeparator: true},
                        {title: "Print", enabled: false, keyTitle: "Ctrl+P", icon: "icons/16/printer3.png"}
                    ]
                }
                ,
                {
                    title: 'Customer',
                    width: 180,
                    showShadow: true,
                    shadowDepth: 10,
                }
                ,
                {
                    title: 'Transaction',
                    width: 180,
                    showShadow: true,
                    shadowDepth: 10,
                }
                ,
                {
                    title: 'Admin',
                    width: 180,
                    showShadow: true,
                    shadowDepth: 10,
                }
            ]
        }),
        isc.HLayout.create({
            members:[
                isc.HTMLFlow.create({
                    ID: "textCanvas",
                    contents: "<h1>Create user</h1><br/><h3>Input required fields</h3>",
                    padding:5,
                    height: 1
                }),
                isc.DynamicForm.create({
                    ID: "exampleForm",
                    width: '100%',
                    colWidths: ['*', '*'],
                    titleOrientation: 'top',
                    fields: [
                        { name: "field01", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field02", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field03", title: "Password", type: "text", width: "*", required: true },
                        { name: "field04", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field05", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field06", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field07", title: "Password", type: "text", width: "*", required: true },
                        { name: "field08", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field09", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field10", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field11", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field12", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field13", title: "Password", type: "text", width: "*", required: true },
                        { name: "field14", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field15", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field16", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field17", title: "Password", type: "text", width: "*", required: true },
                        { name: "field18", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field19", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field20", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field21", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field22", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field23", title: "Password", type: "text", width: "*", required: true },
                        { name: "field24", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field25", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field26", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field27", title: "Password", type: "text", width: "*", required: true },
                        { name: "field28", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field29", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field30", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field31", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field32", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field33", title: "Password", type: "text", width: "*", required: true },
                        { name: "field34", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field35", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field36", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field37", title: "Password", type: "text", width: "*", required: true },
                        { name: "field38", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field39", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field40", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field41", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field42", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field43", title: "Password", type: "text", width: "*", required: true },
                        { name: "field44", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field45", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field46", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field47", title: "Password", type: "text", width: "*", required: true },
                        { name: "field48", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field49", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field50", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field51", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field52", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field53", title: "Password", type: "text", width: "*", required: true },
                        { name: "field54", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field55", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field56", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field57", title: "Password", type: "text", width: "*", required: true },
                        { name: "field58", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field59", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field60", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field61", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field62", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field63", title: "Password", type: "text", width: "*", required: true },
                        { name: "field64", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field65", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field66", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field67", title: "Password", type: "text", width: "*", required: true },
                        { name: "field68", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field69", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field70", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field71", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field72", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field73", title: "Password", type: "text", width: "*", required: true },
                        { name: "field74", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field75", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field76", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field77", title: "Password", type: "text", width: "*", required: true },
                        { name: "field78", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field79", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field80", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field81", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field82", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field83", title: "Password", type: "text", width: "*", required: true },
                        { name: "field84", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field85", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field86", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field87", title: "Password", type: "text", width: "*", required: true },
                        { name: "field88", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field89", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field90", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field91", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field92", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field93", title: "Password", type: "text", width: "*", required: true },
                        { name: "field94", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field95", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field96", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field97", title: "Password", type: "text", width: "*", required: true },
                        { name: "field98", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field99", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field100", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field101", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field102", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field103", title: "Password", type: "text", width: "*", required: true },
                        { name: "field104", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field105", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field106", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field107", title: "Password", type: "text", width: "*", required: true },
                        { name: "field108", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field109", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field110", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field111", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field112", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field113", title: "Password", type: "text", width: "*", required: true },
                        { name: "field114", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field115", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field116", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field117", title: "Password", type: "text", width: "*", required: true },
                        { name: "field118", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field119", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field120", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field121", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field122", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field123", title: "Password", type: "text", width: "*", required: true },
                        { name: "field124", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field125", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field126", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field127", title: "Password", type: "text", width: "*", required: true },
                        { name: "field128", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field129", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field130", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field131", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field132", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field133", title: "Password", type: "text", width: "*", required: true },
                        { name: "field134", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field135", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field136", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field137", title: "Password", type: "text", width: "*", required: true },
                        { name: "field138", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field139", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field140", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field141", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field142", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field143", title: "Password", type: "text", width: "*", required: true },
                        { name: "field144", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field145", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field146", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field147", title: "Password", type: "text", width: "*", required: true },
                        { name: "field148", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field149", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field150", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field151", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field152", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field153", title: "Password", type: "text", width: "*", required: true },
                        { name: "field154", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field155", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field156", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field157", title: "Password", type: "text", width: "*", required: true },
                        { name: "field158", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field159", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field160", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field161", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field162", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field163", title: "Password", type: "text", width: "*", required: true },
                        { name: "field164", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field165", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field166", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field167", title: "Password", type: "text", width: "*", required: true },
                        { name: "field168", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field169", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field170", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field171", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field172", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field173", title: "Password", type: "text", width: "*", required: true },
                        { name: "field174", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field175", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field201", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field202", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field203", title: "Password", type: "text", width: "*", required: true },
                        { name: "field204", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field205", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field206", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field207", title: "Password", type: "text", width: "*", required: true },
                        { name: "field208", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field209", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field210", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field211", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field212", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field213", title: "Password", type: "text", width: "*", required: true },
                        { name: "field214", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field215", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field216", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field217", title: "Password", type: "text", width: "*", required: true },
                        { name: "field218", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field219", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field220", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field221", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field222", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field223", title: "Password", type: "text", width: "*", required: true },
                        { name: "field224", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field225", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field226", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field227", title: "Password", type: "text", width: "*", required: true },
                        { name: "field228", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field229", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field230", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field231", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field232", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field233", title: "Password", type: "text", width: "*", required: true },
                        { name: "field234", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field235", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field236", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field237", title: "Password", type: "text", width: "*", required: true },
                        { name: "field238", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field239", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field240", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field241", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field242", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field243", title: "Password", type: "text", width: "*", required: true },
                        { name: "field244", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field245", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field246", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field247", title: "Password", type: "text", width: "*", required: true },
                        { name: "field248", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field249", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field250", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field251", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field252", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field253", title: "Password", type: "text", width: "*", required: true },
                        { name: "field254", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field255", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field256", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field257", title: "Password", type: "text", width: "*", required: true },
                        { name: "field258", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field259", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field260", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field261", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field262", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field263", title: "Password", type: "text", width: "*", required: true },
                        { name: "field264", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field265", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field266", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field267", title: "Password", type: "text", width: "*", required: true },
                        { name: "field268", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field269", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field270", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field271", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field272", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field273", title: "Password", type: "text", width: "*", required: true },
                        { name: "field274", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field275", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field276", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field277", title: "Password", type: "text", width: "*", required: true },
                        { name: "field278", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field279", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field280", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field281", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field282", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field283", title: "Password", type: "text", width: "*", required: true },
                        { name: "field284", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field285", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field286", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field287", title: "Password", type: "text", width: "*", required: true },
                        { name: "field288", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field289", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field290", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field291", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field292", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field293", title: "Password", type: "text", width: "*", required: true },
                        { name: "field294", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field295", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        { name: "field296", title: "Email", type: "text", width: "*", required: true, defaultValue: "bob@isomorphic.com"},
                        { name: "field297", title: "Password", type: "text", width: "*", required: true },
                        { name: "field298", title: "Password again", type: "text", width: "*",required: true},
                        { name: "field299", title: "Name", type: "text",  width: "*", required: true, defaultValue: "bob"},
                        {
                            name: "save",
                            title: "Save",
                            type: "button",
                            endRow: false,
                            startRow: true
                        },
                        {
                            name: "cancel",
                            title: "Cancel",
                            type: "button",
                            endRow: false,
                            startRow: false
                        }
                    ]
                })

            ]
        })

    ]
})
